### ISSUE TITLE
docker.errors.ImageNotFound on Unraid

### ISSUE THREAD

**Issue by Pepeanuts** [nicolargo/glances#2233]
**Describe the bug**
Glances wont start working correctly

**Expected behavior**
On logs i've these errors
`

> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
>     response.raise_for_status()
>   File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/3a53aa3cbdb58ae1d11fdc3f845e70ef1c2d1d142b2c72c237fb3ddaf2d743fa/json
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/usr/lib/python3.10/site-packages/glances/__main__.py", line 19, in <module>
>     glances.main()
>   File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
>     start(config=core.get_config(), args=core.get_args())
>   File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
>     mode = GlancesMode(config=config, args=args)
>   File "/usr/lib/python3.10/site-packages/glances/webserver.py", line 31, in __init__
>     self.stats.update()
>   File "/usr/lib/python3.10/site-packages/glances/stats.py", line 216, in update
>     self._plugins[p].update()
>   File "/usr/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1114, in wrapper
>     ret = fct(self, *args, **kw)
>   File "/usr/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1131, in wrapper
>     ret = fct(*args, **kw)
>   File "/usr/lib/python3.10/site-packages/glances/plugins/glances_docker.py", line 255, in update
>     container_stats['Image'] = container.image.tags
>   File "/usr/lib/python3.10/site-packages/docker/models/containers.py", line 40, in image
>     return self.client.images.get(image_id.split(':')[1])
>   File "/usr/lib/python3.10/site-packages/docker/models/images.py", line 335, in get
>     return self.prepare_model(self.client.api.inspect_image(name))
>   File "/usr/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
>     return f(self, resource_id, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/docker/api/image.py", line 251, in inspect_image
>     return self._result(
>   File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
>     self._raise_for_status(response)
>   File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
>     raise create_api_error_from_http_exception(e) from e
>   File "/usr/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation) from e
> docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/3a53aa3cbdb58ae1d11fdc3f845e70ef1c2d1d142b2c72c237fb3ddaf2d743fa/json: Not Found ("no such image: 3a53aa3cbdb58ae1d11fdc3f845e70ef1c2d1d142b2c72c237fb3ddaf2d743fa: No such image: sha256:3a53aa3cbdb58ae1d11fdc3f845e70ef1c2d1d142b2c72c237fb3ddaf2d743fa")

`

**Additional context**
Docker on Unraid.
Delete and fresh install of container dont change anything

**Comment by Pepeanuts** [comment]
after new install : ok
i dont know what happened

**Comment by RazCrimson** [comment]
> after new install : ok
i dont know what happened

The issue seems to be due to python docker client trying to look for image that is not found, I am not sure how that ended up happening tho. 

Maybe you deleted some images while the containers were listed in glances?

**Comment by TadMSTR** [comment]
> 

I had the same thing. However redoing the container did not resolve and now I cannot reproduce that error in the logs. Glances start but nothing loads and the log just show a black screen.

**Comment by RazCrimson** [comment]
@TadMSTR 

So is the issue still present or is it resolved now?

**Comment by TadMSTR** [comment]
> @TadMSTR
> 
> So is the issue still present or is it resolved now?

Yea I am good now. I initially kept getting the same errors in the log so redid the container a few times. At some point I must have also changed the network setting. I had stopped getting those errors and the container was running. Once I finally caught the network setting and changed back to host it was all good.

**Comment by RazCrimson** [comment]
Cool, then could you please close the issue as there are no problems?

**Comment by Jackeldk** [comment]
seems i get the same issue as this, but reinstalling does not help.

reverting to 3.2.7 lets me run it but upgrading to 3.3.0 stops it with this error

system ( unraid )

**Comment by RazCrimson** [comment]
@Jackeldk 
Can you just try to restart glances once?

> The issue seems to be due to python docker client trying to look for image that is not found, I am not sure how that ended up happening tho.
> 
> Maybe you deleted some images while the containers were listed in glances?

As mentioned above, it could be caused by deleting some docker images, while glances in active, but it should be fixed with a simple restart. 

Could try that?

**Comment by RazCrimson** [comment]
Weird, there is no change with the Docker API interaction when we compare `3.2.7` and and the current `develop` 
The only change is some additional sorting options, which should not cause any problems.

@Jackeldk 
What version of docker are you using?

Also, one difference is that `docker` python library version used in glances:3.2.7 is 5.0.3, where as in glances:3.3.1 it is 6.0.1.
So one option would be to open a shell and reinstall docker with `pip install docker==5.0.3` and try launching glances again. The command to exec inside would be:
```sh
docker exec -it <container name or id> /bin/sh
# Now we are inside the container
pip install docker==5.0.3
glances
```
Hopefully this makes it work :)

**Comment by Jackeldk** [comment]
im on unraid so dont think i can update like that

**Comment by stephansmolek** [comment]
I have the same issue. I am also on Unraid. Docker Version is 20.10.21.

Seems to work with an older version (I tried alpine-3.2.6.3)
I have definitely not deleted images after installing, but before.

```
pip install docker==5.0.3
```

in the container also did not fix the issue.

**Comment by RazCrimson** [comment]
@Jackeldk @stephansmolek 

Please try the fix mentioned here:
https://forums.unraid.net/topic/134016-fix-to-a-small-issue-with-updating-oci-docker-images/

Source: https://github.com/nicolargo/glances/discussions/2258#discussioncomment-4834506

**Comment by Jackeldk** [comment]
> @Jackeldk @stephansmolek
> 
> Please try the fix mentioned here: https://forums.unraid.net/topic/134016-fix-to-a-small-issue-with-updating-oci-docker-images/
> 
> Source: [#2258 (comment)](https://github.com/nicolargo/glances/discussions/2258#discussioncomment-4834506)

mine already looks like this.

**Comment by stephansmolek** [comment]
> @Jackeldk @stephansmolek
> 
> Please try the fix mentioned here: https://forums.unraid.net/topic/134016-fix-to-a-small-issue-with-updating-oci-docker-images/
> 
> Source: [#2258 (comment)](https://github.com/nicolargo/glances/discussions/2258#discussioncomment-4834506)

Sadly this does not resolve the issue.

**Comment by RazCrimson** [comment]
@stephansmolek @Jackeldk 

Can you guys check if the following line executes without issues on a Unraid Terminal?
```shell
docker run -it -v /var/run/docker.sock:/var/run/docker.sock:ro python /bin/bash
python -m pip install docker==5.0.3
python3 -c 'import docker; [print(c.image.tags) for c in docker.from_env().containers.list()]'
```
The above lines start a docker container with the docker socket bound to the container, then downloads docker's python lib and then tries to list the image tags of the containers

**Comment by RazCrimson** [comment]
@stephansmolek @Jackeldk @quincy5891 
The docker plugin is failing as the one of the calls to the docker socket is failing with a 404. Specifically the call to retrieve the container image name is failing for some container.

I believe the problem is either with the unraid's packaging or the particular version of docker used by unraid.

I could make a simple patch that would just ignore the error and continue, but then the image name for that container would not be present. The issue would probably fixed when newer versions for the docker engine is released on unraid. 

Is that acceptable for you all?

**Comment by quincy5891** [comment]
That works for me.

**Comment by stephansmolek** [comment]
Sounds good to me.

**Comment by RazCrimson** [comment]
@stephansmolek @quincy5891

Please try out the changes on the latest `develop` branch.

If you are using the docker images, then use the images tagged with `dev`.
They can be found here: https://hub.docker.com/r/nicolargo/glances/tags

**Comment by DrSpaldo** [comment]
FYI, I just noticed my glances was not working either after updating Unraid to 6.11.5. I changed to the :dev tag and it is working again. Thanks
