### ISSUE TITLE
Server password configuration for the browser mode

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#500]
As asked by @xeon927 in the issue https://github.com/nicolargo/glances/issues/498, it should be possible to configure the servers' passwords in the configuration file for the browser mode.

Configuration file sample:

```
[passwords]
default=mydummypassword
xps=myxpspassword
```

**Comment by stephdl** [comment]
Hi nicolas

I will be interested by this new feature, do you have some idea when it will be available ?

Thank in advance

**Comment by nicolargo** [comment]
Hi @stephdl,

the feature is planned in the Glances 2.5 milestone (scheduled in september 2015).

**Comment by xeon927** [comment]
Aw, dang - this is pretty well the one thing stopping me from implementing it on all my servers for monitoring.

Ah well - I can wait xD

**Comment by stephdl** [comment]
Merci Nicolas :)

I'm the packager of a rpm for Nethserver and I will be happy to see this feature too. I tried to use a reverse proxy and protect glances by apache but the css was broken....thus my interest.

**Comment by nicolargo** [comment]
Done in latest commit on the develop branch (Glances 2.5beta).
Can you test and comment please => https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version#use-a-python-virtual-environment-the-easy-and-standard-way ?

**Comment by HLFH** [comment]
Ok big thanks!!! I'm just testing it with Docker: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version#use-a-docker-container ; it seems that the command is wrong: it should be docker instead of docker.io

**Comment by nicolargo** [comment]
Forgot the docker method to test Glances, uses a virtual environment (vitrenv).

**Comment by HLFH** [comment]
Ok thx. I guess if #500 solves the authentication for the browser mode, issue #446 related to the authentication for the webserver mode (glances -w) is not solved with this commit.

**Comment by nicolargo** [comment]
OK, thk for the feedback.

For the issue #446 it is planned in the 2.5 release: @notFloran or @nclsHart Can you have a look ?

**Comment by xeon927** [comment]
Is there any info on how this works? Which host does the password come from (ie, does it read the remote machine's hostname, the set server name, or the alias?) - I've tried all three so far, and don't seem to have much luck. Keep failing to connect, saying it's a bad password.

If it comes to it, would it be easier to integrate it with the rest of the options, instead of in its own [password] block? (ie, server_##_password=clearpassword, etc)

Sorry for being a pain :P

**Comment by nicolargo** [comment]
@xeon927 ; first of all, you have to use the develop branch (read the Wiki here: https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version).

The passwords should be defined in the client's configuration file as following (ex with a client called **xps**):

```
[passwords]
# Define the passwords list
# Syntax: host=password
# Where: host is the hostname
#        password is the clear password
# Additionnaly (and optionnaly) a default password could be defined
xps=abc
default=defaultpassword
```

**Comment by xeon927** [comment]
I've got the develop branch up and running well - had that before my prior message, yet still am getting the issue of it refusing to connect due to an incorrect password.

eg.
Server (develop branch, let's call it `serv01`, alias of `server`, `IP 192.168.1.2`) running as `glances --server --password`, entering the password "abc123", and saving to file.
Client (develop branch, same machine), running as `glances --browser --disable-autodiscover`

Snippets of config as follows:

    [serverlist]
    server_1_name=192.168.1.2
    server_1_alias=server
    server_1_port=61209
    
    [passwords]
    server=abc123
    #added other options (IP and actual machine hostname in case alias is wrong option)
    serv01=abc123
    192.168.1.2=abc123

Doing this still results in the "Bad Password" error as follows:

    2015-06-07 22:55:36,436 -- INFO -- Start Glances 2.5beta
    2015-06-07 22:55:36,437 -- INFO -- CPython 2.7.3 and PSutil 2.2.1 detected
    2015-06-07 22:55:36,459 -- INFO -- Read configuration file '/home/xeon927/.config/glances/glances.conf'
    2015-06-07 22:55:36,460 -- INFO -- Auto discover mode is disabled
    2015-06-07 22:55:36,460 -- INFO -- Start client mode (browser)
    2015-06-07 22:55:36,524 -- INFO -- Start reading the [serverlist] section in the configuration file
    2015-06-07 22:55:36,591 -- INFO -- 1 server(s) loaded from the configuration file
    2015-06-07 22:55:36,592 -- INFO -- Start reading the [passwords] section in the configuration file
    2015-06-07 22:55:36,593 -- INFO -- 3 password(s) loaded from the configuration file
    2015-06-07 22:55:42,114 -- INFO -- Connect Glances client to the 192.168.1.2:61209 server
    2015-06-07 22:55:42,121 -- ERROR -- Connection to server failed (bad password)

Am I doing something wrong?

**Comment by nicolargo** [comment]
Can you start Glances in debug mode (-d) and send us back the log file (extract before the ERROR message) ?

**Comment by xeon927** [comment]
Here's the full error log up until (and including) the error:

    2015-06-08 20:21:53,005 -- INFO -- Start Glances 2.5beta
    2015-06-08 20:21:53,005 -- INFO -- CPython 2.7.3 and PSutil 2.2.1 detected
    2015-06-08 20:21:53,028 -- INFO -- Read configuration file '/home/xeon927/.config/glances/glances.conf'
    2015-06-08 20:21:53,029 -- INFO -- Auto discover mode is disabled
    2015-06-08 20:21:53,029 -- INFO -- Start client mode (browser)
    2015-06-08 20:21:53,078 -- DEBUG -- Zeroconf version 0.17.1 detected.
    2015-06-08 20:21:53,094 -- INFO -- Start reading the [serverlist] section in the configuration file
    2015-06-08 20:21:53,095 -- DEBUG -- Add server 192.168.1.2 to the static list
    2015-06-08 20:21:53,160 -- INFO -- 1 server(s) loaded from the configuration file
    2015-06-08 20:21:53,160 -- DEBUG -- Static server list: [{'username': 'glances', 'status': 'UNKNOWN', 'name': '192.168.1.2', 'ip': '192.168.1.2', 'alias': 'server', 'key': '192.168.1.2:61209', 'password': '', 'type': 'STATIC', 'port': '61209'}]
    2015-06-08 20:21:53,161 -- INFO -- Start reading the [passwords] section in the configuration file
    2015-06-08 20:21:53,162 -- INFO -- 3 password(s) loaded from the configuration file
    2015-06-08 20:21:53,162 -- DEBUG -- Password dictionary: {'server': 'abc123', 'serv01': 'abc123', '192.168.1.2': 'abc123'}
    2015-06-08 20:21:53,169 -- DEBUG -- Servers list: [{'username': 'glances', 'status': 'UNKNOWN', 'name': '192.168.1.2', 'ip': '192.168.1.2', 'alias': 'server', 'key': '192.168.1.2:61209', 'password': '', 'type': 'STATIC', 'port': '61209'}]
    2015-06-08 20:21:53,170 -- DEBUG -- Cannot grab stats load_min5 from server (KeyError: 'load_min5')
    2015-06-08 20:21:53,171 -- DEBUG -- Cannot grab stats cpu_percent from server (KeyError: 'cpu_percent')
    2015-06-08 20:21:53,171 -- DEBUG -- Cannot grab stats mem_percent from server (KeyError: 'mem_percent')
    2015-06-08 20:21:53,172 -- DEBUG -- Cannot grab stats hr_name from server (KeyError: 'hr_name')
    2015-06-08 20:21:55,378 -- DEBUG -- Keypressed (code: [10, -1])
    2015-06-08 20:21:55,378 -- DEBUG -- Server number 1 selected
    2015-06-08 20:21:55,479 -- DEBUG -- Selected server: {'username': 'glances', 'status': 'UNKNOWN', 'name': '192.168.1.2', 'ip': '192.168.1.2', 'alias': 'server', 'key': '192.168.1.2:61209', 'password': '', 'type': 'STATIC', 'port': '61209'}
    2015-06-08 20:21:56,481 -- INFO -- Connect Glances client to the 192.168.1.2:61209 server
    2015-06-08 20:21:56,482 -- DEBUG -- Try to connect to http://192.168.1.2:61209
    2015-06-08 20:21:56,488 -- ERROR -- Connection to server failed (bad password)

**Comment by nicolargo** [comment]
@xeon927 One more think, can you send us the log of the client side ?

**Comment by xeon927** [comment]
@nicolargo That log was from the client. In addition, after starting up the server, even with debug mode enabled, it does not spit out any info on a failed connection. Only the client, which is detailed in the log above :)

**Comment by nicolargo** [comment]
@xeon927 Sorry, the server side ;)

**Comment by xeon927** [comment]
@nicolargo Not a problem - all good. Log is a bit long, so I threw it up on Pastebin: http://pastebin.com/hq0bBYtK

As mentioned just above, when attempting to connect, it doesn't log anything for the server.

**Comment by nicolargo** [comment]
Thk @xeon927 i will have a closer look as soon as possible.

**Comment by xeon927** [comment]
@nicolargo Not a problem :)

**Comment by xeon927** [comment]
Issue has been closed, though still does not work - possibly related: #694
